# <p style='text-align: center;'> Numpy Functions </p>

- "ndarray" is one of the pre-defined class of numpy module and whose object is used for storing the data in 
  numpy programming in the form of 1-D, 2-D and n-Dimensional Arrays.


- In numpy programming, we have the following functions of an object of ndarray.	
	
            1. array()
            2. linspace()
            3. arange()
            4. zeros()
            5. ones()
            6. full()
            7. identity()
            8. eye()
            9. hstack()
           10. vstack()
           11. diag()
           12. ravel()
           13. transpose()
           14. randint()


<b> 1) array() :
- This Function is used for converting Traditional Python Objects into ndarray object.
    
    
- <b> Syntax: -    varname=numpy.array(Object, dtype)
    
    
- Here varname is an object of <class,ndarray>
    
    
- Here array() is pre-defined function of numpy module, used for Converting Traditional Python Objects into ndarray object.


- object represents any Traditional Python Objects.
    
    
- dtype represents any numpy data type such as int8, int16, int32, float16, float32, float64....etc (Internal data types 
  of C lang).
    
    
---------------------
#### Examples
--------------------

In [3]:
# Python Traditional List.

# User given list.
l1=[10,20,30,40,50,60]

# print the list and its type.
print(l1,type(l1))

[10, 20, 30, 40, 50, 60] <class 'list'>


In [4]:
# ndarray object of Numpy Module.

# importing numpy module.
import numpy as np

# create an object of ndarray. 
a=np.array(l1)

# print the ndarray and its type.
print(a,type(a))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [5]:
# Python Traditional tuple.

# User given tuple.
t=(10,20,30,40,50,60,70)

# print the tuple and its type.
print(t,type(t))

(10, 20, 30, 40, 50, 60, 70) <class 'tuple'>


In [6]:
# ndarray object of Numpy Module.

# importing numpy module.
import numpy as np

# create an object of ndarray. 
b=np.array(t)

# print the ndarray and its type.
print(b,type(b))

[10 20 30 40 50 60 70] <class 'numpy.ndarray'>


In [7]:
# Python Traditional dict.

# User given dict.
d1={10:1.2,20:4.5,30:6.7}

# print the dict and its type.
print(d1,type(d1))

{10: 1.2, 20: 4.5, 30: 6.7} <class 'dict'>


In [8]:
# ndarray object of Numpy Module.

# importing numpy module.
import numpy as np

# create an object of ndarray. 
c=np.array(d1)

# print the ndarray and its type.
print(c,type(c))

{10: 1.2, 20: 4.5, 30: 6.7} <class 'numpy.ndarray'>


In [9]:
# User given tule.
t=(10,20,30,40,50,60)

# create an object of ndarray.
a=np.array(t)

# printing "a" ndarray object.
a

array([10, 20, 30, 40, 50, 60])

<b> ndim :
- This array attribute returns the number of array dimensions.
    
    
- <b> Syntax : - ndarrayobj.ndim

In [11]:
# Using ndim to returns the number of array dimensions.
a.ndim

1

<b> shape :
- This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

    
    
- <b> Syntax : - ndarrayobj.shape

In [12]:
# Using shape returns a tuple consisting of array dimensions.
a.shape

(6,)

In [18]:
# shape also used for resizes the ndarray.
# resizing 1D to 2D.

# User given list.
l1=[10,20,30,40,50,60]

# create an object of ndarray. 
a=np.array(l1)

# reshaping "(6,)" to "(2,3)".
a.shape=(2,3)

# print reshaped object.
print(a)

[[10 20 30]
 [40 50 60]]


<b> reshape :
- Reshaping means changing the shape of an array.

    
- By reshaping we can add or remove dimensions or change number of elements in each dimension.
    
    
- <b> Syntax : - newobj=ndarrayobj.reshape(rows,columns)

In [19]:
# reshape the 1D to 2D by using reshape.

# User given list.
l1=[10,20,30,40,50,60]

# create an object of ndarray. 
a=np.array(l1)

# reshaping "(6,)" to "(2,3)".
b=a.reshape(3,2)

# print reshaped object.
print(b)

[[10 20]
 [30 40]
 [50 60]]


In [24]:
# finding ndim for "b" object.
b.ndim                # its 2D object.

2

In [26]:
# finding shape for "b" object.
b.shape         # 3-rows and 2-columns.    

(3, 2)

In [21]:
# User given tuple.
t1=(((10,20,15),(30,40,25)),((50,60,18),(70,80,35)))

# print tuple and its type.
print(t1,type(t1))

(((10, 20, 15), (30, 40, 25)), ((50, 60, 18), (70, 80, 35))) <class 'tuple'>


In [22]:
# Creating ndarray object from tuple object.
a=np.array(t1)

# print the ndarray object.
a

array([[[10, 20, 15],
        [30, 40, 25]],

       [[50, 60, 18],
        [70, 80, 35]]])

In [23]:
# print the ndarray object with print().
print(a)

[[[10 20 15]
  [30 40 25]]

 [[50 60 18]
  [70 80 35]]]


In [27]:
# finding ndim for "a" object.
a.ndim                # its 3D object.

3

In [28]:
# finding shape for "a" object.
a.shape         #  3D, 2-rows and 3-columns. 

(2, 2, 3)

<b> 2. linspace() :
- linspace returns evenly spaced numbers over a specified interval.


- <b> Syntax : - np.linspace(start,end,num_of_samples)
    

In [35]:
# Python Programming for demonstrating linspace() method.

# import numpy module.
import numpy as np

# start=0
# end=100
# num_of_samples=11
# Creating and displying the linspace result.
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

<b> 3. arange() :
- It creates an array by using the evenly spaced values over the given interval.


- <b> Syntax3:-  varname=numpy.arange(Start,Stop,Step)


- Here var name is an object of <class,ndarray>.
    
    
- start : [optional] start of interval range. By default start = 0
    
    
- stop  : end of interval range. creates an object of ndarray with the values from Start to Stop-1.

    
    
- step  : [optional] step size of interval. By default step size = 1.


- arange() always create an object of ndarray in 1-D array only but not Possible to create directly 2-D and Multi-Dimensional 
  Arrays.

    
- To create 2-D and Multi-Dimensional Arrays, we must use reshape() or shape attribute.


In [37]:
# Python Programming for domenstrating arange() method.
 
# importing the numpy module.
import numpy as np
 
# Printing all numbers from 1 to 5 in steps of 0.5
print(np.arange(1, 5, 0.5))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [41]:
# Python Programming for domenstrating arange() method.
 
# importing the numpy module.
import numpy as np

# creating arange object as "a" with,
# start=10
# stop=81
# step=10
a=np.arange(10,81,10)

# Printing "a" object and its type.
print(a,type(a))

[10 20 30 40 50 60 70 80] <class 'numpy.ndarray'>


In [40]:
# printing ndim for "a" object.
a.ndim         # its 1D.

1

In [43]:
# Converting 1D to 2D and storing in "b" object.
b=a.reshape(2,4)

# printing the "b" object.
print(b)

[[10 20 30 40]
 [50 60 70 80]]


In [44]:
# printing ndim for "b" object.
b.ndim         # its 2D.

2

In [45]:
# printing shape for "b" object.
b.shape        # its  2D, 2-rows and 4-columns.

(2, 4)

In [49]:
# Converting 1D to 3D and storing in "c" object.
c=a.reshape(2,2,2)

# printing the "c" object.
print(c)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [50]:
# printing ndim for "c" object.
c.ndim         # its 3D.

3

In [51]:
# printing shape for "c" object.
c.shape        # its  3D, 2-rows and 2-columns.

(2, 2, 2)

In [52]:
# If we are trying to convert 1D (8,) to 2D (3,3).
# Then we get ValueError.
d=a.reshape(3,3)

# printing the "b" object.
print(d)

ValueError: cannot reshape array of size 8 into shape (3,3)

- In above example we got "ValueError" bcoz, a object contains 8 elements, we are trying to create 9 elements 2D object,
  so its not possible.

<b> 4. zeros() :
- This Function is used for building ZERO matrix either with 1-D or 2-D or n-D.


- <b> Syntax: -  varname=numpy.zeros(shape,dtype)
    
    
- Here Shape can be 1-D (number of Zeros)  or 2-D (Rows, Cols) or n-D (Number of Matrices, Number of Rows, Number of Columns).


In [58]:
# Python Programming for domenstrating 1D zeros() method.
 
# importing the numpy module.
import numpy as np

# creating 1D zeros object with 6 zeros.
a=np.zeros(6,)     # dtype is optional

# Printing "a" object and its type.
print(a,type(a))    # by default dtype returns float.

[0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [59]:
# printing ndim for "a" object.
a.ndim         # its 1D.

1

In [60]:
# printing shape for "a" object.
a.shape        # its  (6, ).

(6,)

In [61]:
# Python Programming for domenstrating 1D zeros() method with int.
 
# importing the numpy module.
import numpy as np

# creating 1D zeros object with 6 zeros.
a=np.zeros(6,dtype=int)    # dtype=int

# Printing "a" object and its type.
print(a,type(a)) 

[0 0 0 0 0 0] <class 'numpy.ndarray'>


In [62]:
# printing ndim for "a" object.
a.ndim         # its 1D.

1

In [63]:
# printing shape for "a" object.
a.shape        # its  (6, ).

(6,)

In [64]:
# Python Programming for domenstrating 2D zeros() method.
 
# importing the numpy module.
import numpy as np

# creating 2D zeros object with (4,2) shape.
b=np.zeros((4,2),dtype=int)    # dtype=int

# Printing "b" object and its type.
print(b,type(b)) 

[[0 0]
 [0 0]
 [0 0]
 [0 0]] <class 'numpy.ndarray'>


In [65]:
# printing ndim for "b" object.
b.ndim         # its 2D.

2

In [67]:
# printing shape for "b" object.
b.shape        # its 4-rows, 2-columns.

(4, 2)

In [72]:
# Python Programming for domenstrating 3D zeros() method.
 
# importing the numpy module.
import numpy as np

# creating 3D zeros object with (3,3,4) shape.
c=np.zeros((3,3,4),dtype=int)    # dtype=int

# Printing "c" object and its type.
print(c,type(c)) 

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]] <class 'numpy.ndarray'>


In [71]:
# printing ndim for "c" object.
c.ndim         # its 3D.

3

In [73]:
# printing shape for "c" object.
c.shape        # its 3D, 3-matrix, (3-rows and 4-columns for each matrix).

(3, 3, 4)

<b> 5. ones() :
- This Function is used for building ONEs matrix either with 1-D or 2-D or n-D.


<b> - Syntax:   varname=numpy.ones(shape,dtype)
    
    
- Here Shape can be 1-D (number of ones)  or 2-D (Rows, Cols) or n-D (Number of Matrices, Number of Rows, Number of Columns).


In [76]:
# Python Programming for domenstrating 1D ones() method.
 
# importing the numpy module.
import numpy as np

# creating 1D ones object with 8 ones.
a=np.ones(8,)     # dtype is optional

# Printing "a" object and its type.
print(a,type(a))    # by default dtype returns float.

[1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [77]:
# printing ndim for "a" object.
a.ndim         # its 1D.

1

In [78]:
# printing shape for "a" object.
a.shape        # its number of ones=8 (8, )

(8,)

In [79]:
# Python Programming for domenstrating 2D ones() method with int.
 
# importing the numpy module.
import numpy as np

# creating 2D ones object with 12 ones.
b=np.ones((3,4,),dtype=int)     # dtype=int

# Printing "b" object and its type.
print(b,type(b))    

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] <class 'numpy.ndarray'>


In [80]:
# printing ndim for "b" object.
b.ndim         # its 2D.

2

In [81]:
# printing shape for "b" object.
b.shape        # its (3-rows, 4-columns).

(3, 4)

In [82]:
# Python Programming for domenstrating 3D ones() method with int.
 
# importing the numpy module.
import numpy as np

# creating 2D ones object with 12 ones.
c=np.ones((2,2,3,),dtype=int)     # dtype=int

# Printing "c" object and its type.
print(c,type(c)) 

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] <class 'numpy.ndarray'>


In [83]:
# printing ndim for "c" object.
c.ndim         # its 3D.

3

In [84]:
# printing shape for "c" object.
c.shape        # its (2-matrix, 2-rows, 3-columns).

(2, 2, 3)

<b> 6. full() :
- This function is used for building a matrix by specifying fill value either 1-D or 2-D or n-D.

    
- <b> Syntax:-   varname=numpy.full(shape,fill_value,dtype)
    
    
- Here varname is an object of <class, numpy.ndarray>
    
    
- Here Shape can be 1-D (number of values)  or 2-D (Rows, Cols) or n-D (Number of Matrices, Number of Rows, Number of Columns). 

    
- fill value can be any number of programmer choice.
    

In [85]:
# Python Programming for domenstrating 1D full() method.
 
# importing the numpy module.
import numpy as np

# creating 1D ones object with 5 threes(3's).
a=np.full(5,3)     # dtype is optional

# Printing "a" object and its type.
print(a,type(a))    # by default dtype returns int.

[3 3 3 3 3] <class 'numpy.ndarray'>


In [86]:
# printing ndim for "a" object.
a.ndim         # its 1D.

1

In [87]:
# printing shape for "a" object.
a.shape        # its number of threes=5 (5, )

(5,)

In [89]:
# Python Programming for domenstrating 2D full() method .
 
# importing the numpy module.
import numpy as np

# creating 2D ones object with 12 threes(3's).
b=np.full((3,4),3)     # dtype is optional

# Printing "b" object and its type.
print(b,type(b))    # by default dtype returns int.

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]] <class 'numpy.ndarray'>


In [90]:
# printing ndim for "b" object.
b.ndim         # its 2D.

2

In [91]:
# printing shape for "b" object.
b.shape        # its 3-rows and 4-columns.

(3, 4)

In [93]:
# Python Programming for domenstrating 3D full() method .
 
# importing the numpy module.
import numpy as np

# creating 2D ones object with 12 six's(6's).
c=np.full((3,2,2),6)     # dtype is optional

# Printing "c" object and its type.
print(c,type(c))    # by default dtype returns int.

[[[6 6]
  [6 6]]

 [[6 6]
  [6 6]]

 [[6 6]
  [6 6]]] <class 'numpy.ndarray'>


In [94]:
# printing ndim for "c" object.
c.ndim         # its 3D.

3

In [96]:
# printing shape for "c" object.
c.shape        # its 3-matrix, 2-rows and 2-columns.

(3, 2, 2)

<b> 7. identity() :
- identity returns a square matrix (special case of a 2D-array) which is an identity matrix with the main diagonal (i.e. 'k=0')
  as 1's and the other values as 0's. you can't change the diagonal k here.
    
    
- <b> Syntax: -  varname=numpy.identity(N,dtype)
    
    
- Here N represents Either we can take Rows or Columns and PVM takes as NXN Matrix (Square Matrix--Unit or Identity).


In [97]:
# Python Programming for domenstrating identity() method.
 
# importing the numpy module.
import numpy as np

# creating 2D (3X3) identity() object.
a=np.identity(3,dtype=int)   # by default dtype is float.

# Printing "a" object and its type.
print(a,type(a))      # it will takes diagonal's="1" and other values as "0"


[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'>


In [98]:
# Python Programming for domenstrating identity() method.
 
# importing the numpy module.
import numpy as np

# creating 2D (6X6) identity() object.
a=np.identity(6,)   # by default dtype is float.

# Printing "a" object and its type.
print(a,type(a))      # it will takes diagonal's="1" and other values as "0"


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] <class 'numpy.ndarray'>


<b> 8. eye() :
- returns a 2D-array, which fills the diagonal, i.e. 'k' which can be set, with 1's and rest with 0's.
    
                      (OR)
- Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    
- <b> Syntax : - varname=numpy.eye(N, M=None, k=0, dtype=<class 'float'>)
    
    
- Here N : Number of rows in the output.
    
    
- Here M : Number of columns in the output. If None, defaults to N. N is Optional.
    
    
- Here k : Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, 
  and a negative value to a lower diagonal. (Optional).
    
    
- Here dtype : Data-type of the returned array, by default data type is "float".

In [101]:
# Python Programming for domenstrating eye() method.
 
# importing the numpy module.
import numpy as np

# creating 2D (2X2) eye() object.
a=np.eye(2,dtype=int)   # by default dtype is float.

# Printing "a" object and its type.
print(a,type(a))      # it will takes diagonal's="1" and other values as "0"

[[1 0]
 [0 1]] <class 'numpy.ndarray'>


In [100]:
# printing ndim for "a" object.
a.ndim         # its 2D.

2

In [102]:
# Python Programming for domenstrating eye() method.
 
# importing the numpy module.
import numpy as np

# creating 2D (5X3) eye() object.
b=np.eye(5,3)   # by default dtype is float.

# Printing "b" object and its type.
print(b,type(b))      # it will takes diagonal's="1" and other values as "0"

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [104]:
# Python Programming for domenstrating eye() method.
 
# importing the numpy module.
import numpy as np

# creating 2D (5X5) eye() object.
c=np.eye(5,5,k=1)   # by default dtype is float.

# Printing "c" object and its type.
print(c,type(c))      # it will takes diagonal's="1" and other values as "0"

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'>


- In above example I have changed the diagonal index as 1 (k=1). Thats why it takes index=1 as diagonal.

<b> 9. hstack() :
- Numpy hstack() function in Python is used to stack or concatenate arrays in sequence horizontally (column-wise).


- This process is similar to concatenate arrays along the second axis, except for 1-D arrays where it concatenates along the 
  first axis. It stacks a sequence of two or more arrays into a single Numpy array.

    
- <b> Syntax: - varname=numpy.hstack(tup)
    
    
- Here varname is an object of <class, numpy.ndarray>


- Here tup it contains a sequence of arrays of the same shape. these arrays are to be concatenated as a parameter and return 
  a single Numpy array.


In [109]:
# WAPP to demonstrate hstack on 1-D array.

# importing the numpy module.
import numpy as np

'''create two 1-dimensional arrays of length three and then 
   horizontally stacked them with the hstack() function.'''

# Create two NumPy arrays. 
arr = np.array([ 2, 3, 4])

arr1 = np.array([5, 6, 7])

# Use NumPy.hstack() Functions for concatenation.
arr2 = np.hstack((arr,arr1))

# print the result.
print(arr2)

[2 3 4 5 6 7]


In [110]:
# printing ndim for "arr2" object.
arr2.ndim         # its 1D.

1

In [111]:
# WAPP to demonstrate hstack on 2-D array.

# importing the numpy module.
import numpy as np

'''Here we stacked two 2d arrays of shape (2, 3) horizontally 
   resulting in an array of shape (2, 6).'''

# creating an 2D input arrays. 
arr =  np.array([[ 2, 3, 5], [ -1, -3, -5]])

arr1 = np.array([[ 6, 8, 10], [ -7, -8, -9]])


# Use NumPy.hstack() Functions for concatenation.
arr2 = np.hstack((arr,arr1))

# print the result.
print(arr2)

[[ 2  3  5  6  8 10]
 [-1 -3 -5 -7 -8 -9]]


In [112]:
# printing ndim for "arr2" object.
arr2.ndim         # its 2D.

2

In [114]:
# WAPP to demonstrate concatenate() on 2-D array.

# importing the numpy module.
import numpy as np

'''Here we stacked two 2d arrays of shape (2, 3) horizontally 
   resulting in an array of shape (2, 6).'''

# creating an 2D input arrays. 
arr =  np.array([[ 2, 3, 5], [ -1, -3, -5]])

arr1 = np.array([[ 6, 8, 10], [ -7, -8, -9]])


# Use NumPy.hstack() Functions for concatenation.
arr2 = np.concatenate((arr,arr1),axis=1)

# print the result.
print(arr2)

[[ 2  3  5  6  8 10]
 [-1 -3 -5 -7 -8 -9]]


<b> concatenate() and (hstack, vstack) functions are same. We can use concatenate() it gives same result as hstack or vstack.
- <b> Syntax for concatenate() : numpy.concatenate((a,b),axis=1 or axis=0)
    
    
- Here "a and b" are individual ndarray objects.
    
    
- axis=1 means hstack or column_wise.
    
    
- axis=0 means vstack or row_wise.

<b> 10. vstack() :
- Numpy vstack() function in Python is used to stack or concate the sequence of given arrays vertically(row-wise).


- This process is similar to concatenate arrays along the second axis, except for 1-D arrays where it concatenates along the 
  first axis. It stacks a sequence of two or more arrays into a single Numpy array.

    
    
- <b> Syntax: - varname=numpy.hstack(tup)
    
    
- Here varname is an object of <class, numpy.ndarray>


- Here tup it contains a sequence of arrays of the same shape. these arrays are to be concatenated as a parameter and return 
  a single Numpy array.
    

In [116]:
# WAPP to demonstrate vstack on 1-D array.

# importing the numpy module.
import numpy as np

'''create two 1-dimensional arrays of length three and then 
   vertically stacked them with the vstack() function.'''

# Create two NumPy arrays. 
arr = np.array([ 2, 3, 4])

arr1 = np.array([5, 6, 7])

# Use NumPy.vstack() Functionss for concatenation.
arr2 = np.vstack((arr,arr1))

# print the result.
print(arr2)

[[2 3 4]
 [5 6 7]]


In [117]:
# printing ndim for "arr2" object.
arr2.ndim         # its 2D.

2

In [118]:
# WAPP to demonstrate vstack on 2-D array.

# importing the numpy module.
import numpy as np

'''Take 2-D Numpy arrays and pass them into this function as a 
   parameter, it will return the single 2-D array.'''

# creating an 2D input arrays. 
arr =  np.array([[ 2, 3, 5], [ -1, -3, -5]])

arr1 = np.array([[ 6, 8, 10], [ -7, -8, -9]])


# Use NumPy.vstack() Functions for concatenation.
arr2 = np.vstack((arr,arr1))

# print the result.
print(arr2)

[[ 2  3  5]
 [-1 -3 -5]
 [ 6  8 10]
 [-7 -8 -9]]


In [119]:
# printing ndim for "arr2" object.
arr2.ndim         # its 2D.

2

In [120]:
# WAPP to demonstrate vstack on 3-D array.

# importing the numpy module.
import numpy as np

'''take two 3-D arrays of shapes (2, 2, 2) and apply this 
   function, it will return a single 3-D array of shapes (4, 2, 2).'''

# creating an 3D input arrays. 
arr = np.array([[[1, 3], [2, 4]], [[3, 5], [5, 7]]])

arr1 = np.array([[[4, 1], [5, 7]], [[6, 8],[3, 5]]])



# Use NumPy.vstack() Functions for concatenation.
arr2 = np.vstack((arr,arr1))

# print the result.
print(arr2)

[[[1 3]
  [2 4]]

 [[3 5]
  [5 7]]

 [[4 1]
  [5 7]]

 [[6 8]
  [3 5]]]


In [121]:
# printing ndim for "arr2" object.
arr2.ndim         # its 2D.

3

<b> 11. diag() :
- The diag() function is used to extract a diagonal or construct a diagonal array.


- <b> Syntax : - varname=numpy.diag(v, k=0)
    
    
- Here v : If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on 
  the k-th diagonal.


- Here k : Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal,
  and k<0 for diagonals below the main diagonal.

In [122]:
# WAPP to demonstrate diag() on 2-D array.

# importing the numpy module.
import numpy as np

# Create 2D NumPy array with diagonals as (1,2,3). 
a=np.diag([1,2,3])

# print the result.
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [123]:
# WAPP to extract the diagonals from 2-D array.

# importing the numpy module.
import numpy as np

# etracting diagonals from "a" object.
np.diag(a)

array([1, 2, 3])

<b> 12. ravel() :
- ravel() is used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array.


- The returned array has the same data type as the source array or input array.


- <b> Syntax : - varname=numpy.ravel(x,) 
    
    
- Here x : This parameter defines the input array, which we want to change in a contiguous flattened array. 
  The array elements are read in the order specified by the order parameter and packed as a 1-D array.

In [125]:
# WAPP to demonstrate the ravel() function on 2D arrays.

# importing the numpy module.
import numpy as np

# created an array 'a' using np.array() function.
a=np.array([[1,2,3],[4,5,6]])

# declareing variable 'b' and assigned the returned value of np.ravel() function.
b=np.ravel(a)

# print the value of 'b'.
print(b)

[1 2 3 4 5 6]


In [127]:
# WAPP to demonstrate the ravel() function on 3D arrays.

# importing the numpy module.
import numpy as np

# created an array 'x' using np.array() function.
x=np.array([[[11,12,13]],[[14,15,16]],[[17,18,19]]])

# declareing variable 'z' and assigned the returned value of np.ravel() function.
z=np.ravel(x)

# print the value of 'z'.
print(z)

[11 12 13 14 15 16 17 18 19]


<b> 13. transpose() :
- The numpy.transpose() function changes the row elements into column elements and the column elements into row elements. 
  The output of this function is a modified array of the original one.
    
    
- <b> Syntax : - varname=numpy.transpose(arr, axis=None)  
    
    
- Here 'arr' : It is an ndarray. It is the source array whose elements we want to transpose. This parameter is essential and 
  plays a vital role in numpy.transpose() function.


- Here axis : If we didn't specify the axis, then by default, it reverses the dimensions otherwise permute the axis according  
  to the given values.
    

In [141]:
# WAPP to demonstrate the transpose() function on 2D array.

# importing the numpy module.
import numpy as np

# created an array 'a' using np.array() function.
a=np.array([[1,2,3],[4,5,6]])

# print the value of 'a'.
print("a array containts")
print(a)

print("-"*50)
print("-"*50)

# declareing variable 'b' and assigned the returned value of np.transpose() function.
b=np.transpose(a)

# print the value of 'b'.
print("b array containts")
print(b)

a array containts
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
--------------------------------------------------
b array containts
[[1 4]
 [2 5]
 [3 6]]


In [142]:
# WAPP to demonstrate the transpose() function on 3D array.

# importing the numpy module.
import numpy as np

# created an array 'a' using np.array() function.
c=np.array([[[21,22,23]],[[24,25,26]],[[11,12,13]]])

# print the value of 'c'.
print("c array containts")
print(c)

print("-"*50)
print("-"*50)

# declareing variable 'd' and assigned the returned value of np.transpose() function.
d=np.transpose(c)

# print the value of 'd'.
print("d array containts")
print(d)

c array containts
[[[21 22 23]]

 [[24 25 26]]

 [[11 12 13]]]
--------------------------------------------------
--------------------------------------------------
d array containts
[[[21 24 11]]

 [[22 25 12]]

 [[23 26 13]]]


<b> 14. randint() :
- randint() returns random integers from start (inclusive) to end (exclusive).
    
    
- <b> Syntax : - numpy.random.randint(start, end, no_of_samples).
    
    
- start : [optional] start of interval range. By default start = 0.
    
    
- end : end of interval range. creates an object of ndarray with the values from Start to end-1.
    
    
- no_of_samples : How many random numbers do you want to display.
    

In [7]:
# WAPP to demonstrate randint() on 1D array.

# importing the numpy module.
import numpy as np


# Get the 5 random integers of array from "1" to "10" 
arr = np.random.randint(1,11,5)

# print the result.
print(arr)


[5 3 2 8 5]


In [8]:
# printing ndim for "arr" object.
arr.ndim         # its 1D.

1

In [9]:
# WAPP to demonstrate randint() on 2D array.

# importing the numpy module.
import numpy as np


# Get the "size=(2X4)" random integers of array from "1" to "8". 
arr = np.random.randint(1,9,size=(2, 4))

# print the result.
print(arr)


[[4 8 8 7]
 [5 4 5 8]]


In [10]:
# printing ndim for "arr" object.
arr.ndim         # its 2D.

2

In [11]:
# WAPP to demonstrate randint() on 3D array.

# importing the numpy module.
import numpy as np


# Get the "size=(2X3X4)" random integers of array from "1" to "8". 
# 2-matrixes with 3-rows, 4-columns.
arr = np.random.randint(1,9,size=(2,3,4))

# print the result.
print(arr)

[[[8 4 5 4]
  [5 4 7 7]
  [7 4 5 3]]

 [[8 5 1 5]
  [3 2 1 6]
  [5 7 3 5]]]


In [12]:
# printing ndim for "arr" object.
arr.ndim         # its 3D.

3