# <p style='text-align: center;'> Numpy---Basic Indexing </p>

- If we want to access Single element of 1D, 2D and N-D arrays we must use the concept of Basic Indexing.

--------------------------
### Accessing Single Element 1D-Array:
----------------------------
- <b> Syntax: -     ndarrayname [Index]
    
    
- Here 'index' can be either +ve or -ve indexing.
    

In [1]:
# WAPP which will access a single elements from 1D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([10,20,30,40,50,60])

# print the ndarray and its type.
print(a,type(a))

# Accessing the "20" value from "a" object.
a[1]       # putting index=1 in arrayobj.

[10 20 30 40 50 60] <class 'numpy.ndarray'>


20

In [17]:
# Accessing the "50" value from "a" object.
a[4]       # putting index=4 in arrayobj.

50

In [18]:
# Accessing the "30" value from "a" object by (-ve) indexing.
a[-4]       # putting index=-4 in arrayobj.

30

--------------------------
### Accessing single Element of 2D-Array :
----------------------------
- <b> Syntax: -  ndarrayobj[row index, column index] 
        

In [2]:
# WAPP which will access a single elements from 2D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
b=np.array([[1,2,3],[4,5,6]])

# print the ndarray and its type.
print(b,type(b))

# Accessing the "4" value from "b" object.
b[1,0]       # putting index=[1,0] in arrayobj.
             # Here row-index=1 and col-index=0

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


4

In [20]:
# Accessing the "3" value from "b" object.
b[0,2]       # putting index=[0,2] in arrayobj.
             # Here row-index=0 and col-index=2

3

------------------------------------------------------
### Accessing single Element of 3D-Array :
----------------------------------------------------
- <b> Syntax: - ndarrayobj[Index of matrix, row index, column index]

In [8]:
# WAPP which will access a single elements from 3D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
c=np.array([[[11,12,13]],[[14,15,16]],[[7,8,9]]])

# print the ndarray and its type.
print(c,type(c))

# Accessing the "8" value from "c" object.
c[2,0,1]       # putting index=[2,0,1] in arrayobj.
             # Here matrix-index=2, row-index=0 and col-index=1.

[[[11 12 13]]

 [[14 15 16]]

 [[ 7  8  9]]] <class 'numpy.ndarray'>


8

# <p style='text-align: center;'> Numpy Slicing Operations of 1D,2D and 3D array </p>

------------------------------
### 1D Arrays Slicing :
------------------------------
- <b> Syntax: -   1Dndrrayobj[begin:end:step]

In [10]:
# WAPP which will access a multiple elements (Slicing) from 1D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([10,20,30,40,50,60])

# print the ndarray and its type.
print(a,type(a))

# Accessing the "10 20 30" values only from "a" object.
a[0:3]       # putting begin-index=0 and end-index=3 in arrayobj.

[10 20 30 40 50 60] <class 'numpy.ndarray'>


array([10, 20, 30])

-------------------------------
### 2D Arrays Slicing :
------------------------------
- <b> Syntax: -       2Dndrrayobj[Row Index, Column Index]
                   (OR)
- <b> Syntax: -       2Dndrrayobj[begin:end:step, begin:end:step]

 

In [12]:
# WAPP which will access a multiple elements (Slicing) from 2D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
b=np.array([[1,2,3],[4,5,6]])

# print the ndarray and its type.
print(b,type(b))

# Accessing the "[[1,2],[4,5]]" values from "b" object.
b[0:2,0:2]       # putting index=[0:2,0:2] in arrayobj.
             # Here row-index=[0:2] and col-index=[0:2]

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


array([[1, 2],
       [4, 5]])

-------------------------------------
### 3D Arrays Slicing :
-------------------------------------
- <b> Syntax: -      3Dndrrayobj[Matrix Index, Row Index, Column Index]
				(OR)
- <b> Syntax: -      3Dndrrayobj[begin:end:step, begin:end:step,begin:end:step]


In [16]:
# WAPP which will access a multiple elements (-ve Slicing) from 3D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
c=np.array([[[11,12,13]],[[14,15,16]],[[7,8,9]]])

# print the ndarray and its type.
print(c,type(c))

# Accessing the "[[[12, 13]],[[15, 16]],[[ 8,  9]]])" values from "c" object.
c[-3:,::,-2:]       # putting index=[-3:,::,-2:] in arrayobj.
             # Here matrix-index=[-3: ], row-index=[ :: ] and col-index=[-2: ].

[[[11 12 13]]

 [[14 15 16]]

 [[ 7  8  9]]] <class 'numpy.ndarray'>


array([[[12, 13]],

       [[15, 16]],

       [[ 8,  9]]])

# <p style='text-align: center;'> Numpy---Advanced Indexing and Slicing </p>

- If we want to access multiple elements, which are not in order (arbitrary elements) of 1D, 2D and N-D arrays we must 
  use the concept of Advanced Indexing.
    
    
- If we want to access the elements based on some condition then we can't use basic indexing and Basic Slicing Operations. To 
  fulfill such type of requirements we must use advanced Indexing.


-----------------------------------
### Accessing Multiple Arbitrary Elements-1D :
-----------------------------------------------
- <b> Syntax: -     ndarrayname [x]
    
    
- Here 'x' can be either ndarray or list which represents required indexes of arbitrary elements.


In [22]:
# WAPP which will access a multiple elements (which are not in order) from 1D array .

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([10,20,30,40,50,60])

# print the ndarray and its type.
print(a,type(a))

# Accessing the 20,40 and 50 values from "a" object.
# Here indexes of 20 40 and 50 are 1 3 4.
'''prepare the list of indexes of arbitrary 
   elements(20,40,50) of ndarray and pass to ndarray.'''
ind=[1,3,4]

# Pass the index list in ndarry object.
a[ind]       

[10 20 30 40 50 60] <class 'numpy.ndarray'>


array([20, 40, 50])

In [23]:
# WAPP which will access a multiple elements (which are not in order) from 1D array .

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([10,20,30,40,50,60])

# print the ndarray and its type.
print(a,type(a))

# Accessing the 10,40 and 60 values from "a" object.
# Here indexes of 10 40 and 60 are 0 3 5.
'''prepare the list of indexes of arbitrary 
   elements(10,40,60) of ndarray and pass to ndarray.'''

a[[0,3,5]] 

[10 20 30 40 50 60] <class 'numpy.ndarray'>


array([10, 40, 60])

In [24]:
# Accessing the 10,20,40 and 60 values from "a" object through (-ve) indexing.
# Here indexes of 10 20 40 and 60 are -6 -5 -3 -1.
'''prepare the list of indexes of arbitrary 
   elements(10,20,40,60) of ndarray and pass to ndarray.'''

a[[-6,-5,-3,-1]] 

array([10, 20, 40, 60])

--------------------------------------------------------
# Accessing Multiple Arbitrary Elements - 2D :
-----------------------------------------------------------
- <b> Syntax: -  ndarrayobj[  [row indexes],[column indexes] ]

In [26]:
# WAPP which will access a multiple elements from 2D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

# print the ndarray and its type.
print(m,type(m))

# Accessing the 2, 7, 11 and 14 values from "m" object.
# Here indexes of 2 7 11 and 14 are [ [0,1,2,3],[1,2,2,1] ].
'''When the above statement is executed, The PVM takes internally as 
   mat[ (0,1), (1,2), (2,2),(3,1) ].'''

m[ [0,1,2,3],[1,2,2,1] ]      

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] <class 'numpy.ndarray'>


array([ 2,  7, 11, 14])

In [28]:
# WAPP which will access a principle diagonal elements from 2D array.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

# print the ndarray and its type.
print(m,type(m))

# Accessing the 1, 6, 11 and 16 values from "m" object.
# Here indexes of 1 6 11 and 16 are [ [0,1,2,3],[0,1,2,3] ].
'''When the above statement is executed, The PVM takes internally as 
   mat[ (0,0), (1,1), (2,2),(3,3) ].'''

m[ [0,1,2,3],[0,1,2,3] ] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] <class 'numpy.ndarray'>
Princile diagonal of 2D array


array([ 1,  6, 11, 16])

---------------------------------------------------
### Accessing Multiple Arbitrary Elements - 3D :
--------------------------------------------------
- <b> Syntax: -  ndarray[[Indexes of 3Dmatrix],[row indexes], [column indexes]]


In [32]:
# WAPP which will access a multiple elements from 3D array.

# importing numpy as alias_name np
import numpy as np

# create a list.
l1=[ [ [1,2,3,4],[5,6,7,8],[9,10,11,12] ],[[13,14,15,16],[17,18,19,20],[21,22,23,24] ] ]

# pass the list in object of ndarray. 
d=np.array(l1)

# print the ndarray and its type.
print(d,type(d))

# Accessing the 1, 14 and 24 values from "d" object.
# Here indexes of 1 14 and 24 are [ [0,1,1],[0,0,2],[0,1,3] ].
'''When the above statement is executed, The PVM takes internally as 
   d[ (0,0,0),(1,0,1),(1,2,3) ].'''

d[ [0,1,1],[0,0,2],[0,1,3] ]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] <class 'numpy.ndarray'>


array([ 1, 14, 24])

In [34]:
# WAPP which will access a multiple elements from 3D array by (-ve) indexing.

# importing numpy as alias_name np
import numpy as np

# create a list.
l1=[ [ [1,2,3,4],[5,6,7,8],[9,10,11,12] ],[[13,14,15,16],[17,18,19,20],[21,22,23,24] ] ]

# pass the list in object of ndarray. 
c=np.array(l1)

# print the ndarray and its type.
print(c,type(c))

# Accessing the 10 and 16 values from "c" object.
# Here -ve indexes of 10 and 16 are [ [-2,-1],[-1,-3],[-3,-1] ].
'''When the above statement is executed, The PVM takes internally as 
   c[ (-2,-1,-3),(-1,-3,-1) ].'''

c[ [-2,-1],[-1,-3],[-3,-1] ]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] <class 'numpy.ndarray'>


array([10, 16])

In [35]:
# finding ndim for "c" object.
c.ndim                # its 3D object.

3

In [36]:
# finding shape for "c" object.
c.shape         # 2- matrixes with 3-rows and 4-columns. 

(2, 3, 4)