# <p style='text-align: center;'> Comparision Operations </p>

- The Python numpy comparison operators and functions used to compare the array items and returns Boolean True or false.


- The Python Numpy comparison functions are greater, greater_equal, less, less_equal, equal, and not_equal. Like any other.



- Python Numpy comparison operators are <, <=, >, >=, ==, != and numpy.array_equal().


- numpy.array_equal(a,b)--- it compares two ndarray objects and returns weither both objects are equal are not.

In [16]:
# WAPP to perform all comparision operations on ndarray objects in numpy.

# importing numpy as alias_name np
import numpy as np

# create three ndarray objects with "a,b and c".
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])

# print the "a" ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# print the "b" ndarray object on console.
print("Containts of ndarray(b):")
print(b)
print("-"*50)

# print the "c" ndarray object on console.
print("Containts of ndarray(c):")
print(c)
print("-"*50)

# Check weither a and b ndarray objects elements are equal are not and print it.
# It will returns "True" if elements equals else returns "False".
# It will compare individual elements from two ndarray objects and return result.
print("Checking a elements are equals to b ndarray elements")
print(a==b)
print("-"*50)

# Check weither a and c ndarray objects elements are equal are not and print it.
# It will returns "True" if elements equals else returns "False".
# It will compare individual elements from two ndarray objects and return result.
print("Checking a elements are equals to c ndarray elements")
print(a==c)
print("-"*50)

# Check weither a elements are greater than b ndarray elements and print it.
# It will returns "True" if elements greater else returns "False".
# It will compare individual elements from two ndarray objects and return result.
print("Checking a elements are greater than b ndarray elements")
print(a>b)
print("-"*50)

# Check weither b elements are greater than c ndarray elements and print it.
# It will returns "True" if elements greater else returns "False".
# It will compare individual elements from two ndarray objects and return result.
print("Checking b elements are greater than c ndarray elements")
print(b>c)
print("-"*50)

# Check weither a elements are lesser than b ndarray elements and print it.
# It will returns "True" if elements greater else returns "False".
# It will compare individual elements from two ndarray objects and return result.
print("Checking a elements are lesser than b ndarray elements")
print(a<b)
print("-"*50)

# Check weither a and b ndarray objects are equal are not and print it.
# It will returns "True" if all elements equals else returns "False".
# It will compare individual elements from two ndarray objects and return result.
# If any one element is not equal then it returns "False".
print("Checking a and b ndarray objects are equal")
print(np.array_equal(a,b))
print("-"*50)

# Check weither a and c ndarray objects are equal are not and print it.
# It will returns "True" if all elements equals else returns "False".
# It will compare individual elements from two ndarray objects and return result.
# If any one element is not equal then it returns "False".
print("Checking a and c ndarray objects are equal")
print(np.array_equal(a,c))
print("-"*50)

Containts of ndarray(a):
[1 2 3 4]
--------------------------------------------------
Containts of ndarray(b):
[5 6 7 8]
--------------------------------------------------
Containts of ndarray(c):
[1 2 3 4]
--------------------------------------------------
Checking a elements are equals to b ndarray elements
[False False False False]
--------------------------------------------------
Checking a elements are equals to c ndarray elements
[ True  True  True  True]
--------------------------------------------------
Checking a elements are greater than b ndarray elements
[False False False False]
--------------------------------------------------
Checking b elements are greater than c ndarray elements
[ True  True  True  True]
--------------------------------------------------
Checking a elements are lesser than b ndarray elements
[ True  True  True  True]
--------------------------------------------------
Checking a and b ndarray objects are equal
False
-----------------------------------