# <p style='text-align: center;'> Creating Filter Directly from ndarray </p>

- To select any element from ndarray object, we have two approaches. They are


<b> Approach-1 :

    
- Prepare Boolean Array (It contains True or False. True represents Condition satisfied and False represents Condition 
  not satisfied].
                         
                         
- <b> Syntax: -   varname=ndarrayobject with condition
                         
                         
- <b> varname is called Boolean array.
                         
                         
- Pass the Boolean Array to the ndarray object. So that we can get those elements from ndarray which satisfies with the entry 
  True(or) we can get those elements from ndarray corresponding True entries of Boolean array.
                         
                         
- <b> Syntax: -   ndarray [Boolean Array]


<b> Approach-2 :
    
    
- In this approach, we directly pass Boolean array values to the ndarray for getting required elements based on condition.
    
    
- <b> Syntax: -   ndarray[ndarrayobject with condition]


In [6]:
# Select the Positive Elements from ndarray.
# Here I am solving with Approach - 1.

# import numpy as alias name.
import numpy as np

# Create a list with +ve and -ve elements.
l=[10,21,-34,23,-45,30,-40]

# print the list on console.
print("Containts of list(l):")
print(l)
print("-"*50)

# create an object of ndarray. 
# pass the list into the ndarry.
a=np.array(l)
print("-"*50)

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Extract the Positive Elements from ndarray object & store in a variable.
b=a>0        # Boolean Array
print("-"*50)

# print the Boolean Array on console.
print("Containts of (b):")
print(b)     # it will returns the "True" or "False".
print("-"*50)

# Pass the Boolean Array to the ndarray object.
print("Positive Elements from ndarray:")
a[b]

Containts of list(l):
[10, 21, -34, 23, -45, 30, -40]
--------------------------------------------------
--------------------------------------------------
Containts of ndarray(a):
[ 10  21 -34  23 -45  30 -40]
--------------------------------------------------
--------------------------------------------------
Containts of (b):
[ True  True False  True False  True False]
--------------------------------------------------
Positive Elements from ndarray:


array([10, 21, 23, 30])

In [8]:
# Select the Negetive Elements from ndarray.
# Here I am solving with Approach - 2.

# import numpy as alias name.
import numpy as np

# Create a list with +ve and -ve elements.
l=[10,21,-34,23,-45,30,-40]

# print the list on console.
print("Containts of list(l):")
print(l)
print("-"*50)

# create an object of ndarray. 
# pass the list into the ndarry.
a=np.array(l)
print("-"*50)

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Pass the Boolean Array to the ndarray object directly.
print("Negative Elements from ndarray:")
a[a<0]         # It will print -ve elements.

Containts of list(l):
[10, 21, -34, 23, -45, 30, -40]
--------------------------------------------------
--------------------------------------------------
Containts of ndarray(a):
[ 10  21 -34  23 -45  30 -40]
--------------------------------------------------
Negative Elements from ndarray:


array([-34, -45, -40])

In [10]:
# Select the Even Elements from ndarray.
# Here I am solving with Approach - 1.

# import numpy as alias name.
import numpy as np

# Create a list with even odd elements.
l1=[11,20,33,31,41,47,46,12,13]

# print the list on console.
print("Containts of list(l1):")
print(l1)
print("-"*50)

# create an object of ndarray. 
# pass the list into the ndarry.
x=np.array(l1)
print("-"*50)

# print the ndarray object on console.
print("Containts of ndarray(x):")
print(x)
print("-"*50)

# Extract the Positive Elements from ndarray object & store in a variable.
y=x%2==0           # Boolean Array
print("-"*50)

# print the Boolean Array on console.
print("Containts of (y):")
print(y)     # it will returns the "True" or "False".
print("-"*50)

# Pass the Boolean Array to the ndarray object.
print("Even Elements from ndarray:")
x[y]

Containts of list(l1):
[11, 20, 33, 31, 41, 47, 46, 12, 13]
--------------------------------------------------
--------------------------------------------------
Containts of ndarray(x):
[11 20 33 31 41 47 46 12 13]
--------------------------------------------------
--------------------------------------------------
Containts of (y):
[False  True False False False False  True  True False]
--------------------------------------------------
Even Elements from ndarray:


array([20, 46, 12])

In [11]:
# Select the Odd Elements from ndarray.
# Here I am solving with Approach - 2.

# import numpy as alias name.
import numpy as np

# Create a list with even odd elements.
l1=[11,20,33,31,41,47,46,12,13]

# print the list on console.
print("Containts of list(l1):")
print(l1)
print("-"*50)

# create an object of ndarray. 
# pass the list into the ndarry.
a=np.array(l1)
print("-"*50)

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Pass the Boolean Array to the ndarray object directly.
print("Odd Elements from ndarray:")
a[a%2!=0]         # It will print Odd elements.

Containts of list(l1):
[11, 20, 33, 31, 41, 47, 46, 12, 13]
--------------------------------------------------
--------------------------------------------------
Containts of ndarray(a):
[11 20 33 31 41 47 46 12 13]
--------------------------------------------------
Odd Elements from ndarray:


array([11, 33, 31, 41, 47, 13])