# <p style='text-align: center;'> Numpy delete rows and columns of ndarray </p>

- Python’s Numpy library provides a method to delete elements from a numpy array based on index position i.e.


- <b> Syntax: - numpy.delete(arr, obj, axis=None)
    
    
- arr : Numpy ndarray from which elements needs to be deleted.
    
    
- obj : Index position or list of index positions of items to be deleted from numpy ndarray arr.

    
- axis: Axis along which we want to delete.
    
    
- If 1 then delete columns.


- If 0 then delete rows.


--------------------
### Examples:
--------------------

In [1]:
# WAPP to delete the single values from given (1D) ndarray by using delete() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Delete element at index position 2.
a=np.delete(a,2)      # its delete the index position 2 = 6.

# print the modified ndarray object on console.
print('Modified Numpy Array by deleting element at index position 2')
print(a)       

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
Modified Numpy Array by deleting element at index position 2
[ 4  5  7  8  9 10 11]


In [4]:
# WAPP to delete the single values from given (1D) ndarray by using delete() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Delete element at index position -4.
a=np.delete(a,-4)      # its delete the index position -4 = 8.

# print the modified ndarray object on console.
print('Modified Numpy Array by deleting element at index position -4')
print(a)   

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
Modified Numpy Array by deleting element at index position -4
[ 4  5  6  7  9 10 11]


In [3]:
# WAPP to delete the multiple values from given (1D) ndarray by using delete() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Delete element at index position 1 3 and 6.
# place these indexes in one list and pass to delete function.
a=np.delete(a,[1,3,6])      # its delete the index position 1=5 3=7 6=10.

# print the modified ndarray object on console.
print('Modified Numpy Array by deleting elements at index position 1 3 6')
print(a)  

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
Modified Numpy Array by deleting elements at index position 1 3 6
[ 4  6  8  9 11]


------------------------------------------------
### Delete rows & columns from a 2D Numpy Array
--------------------------------------------------

In [5]:
# WAPP to delete a single column from a 2D numpy array using np.delete().

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
m=np.array([[11 ,12, 13, 11],[21, 22, 23, 24],[31, 32, 33, 34]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(m)
print("-"*50)

# Delete elements from column index 1.
# pass the axis=1 along with numpy array for column deletion.
m=np.delete(m, 1, axis=1)     # its delete the column index position 1.

# print the modified ndarray object on console.
print('Modified 2D Numpy Array by removing columns at index 1')
print(m) 

Containts of ndarray(a):
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
--------------------------------------------------
Modified 2D Numpy Array by removing columns at index 1
[[11 13 11]
 [21 23 24]
 [31 33 34]]


In [6]:
# WAPP to delete a multiple columns from a 2D numpy array using np.delete().

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
m=np.array([[11 ,12, 13, 11],[21, 22, 23, 24],[31, 32, 33, 34]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(m)
print("-"*50)

# Delete elements from column index 2 and 3.
# place these indexes in one list and pass to delete function.
# pass the axis=1 along with numpy array for column deletion.
m=np.delete(m, [2,3], axis=1)  # its delete the column index position 2 and 3.

# print the modified ndarray object on console.
print('Modified 2D Numpy Array by removing columns at index 2 and 3')
print(m) 

Containts of ndarray(a):
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
--------------------------------------------------
Modified 2D Numpy Array by removing columns at index 2 and 3
[[11 12]
 [21 22]
 [31 32]]


In [8]:
# WAPP to delete a single row from a 2D numpy array using np.delete().

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
m=np.array([[11 ,12, 13, 11],[21, 22, 23, 24],[31, 32, 33, 34]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(m)
print("-"*50)

# Delete elements from row index 0.
# pass the axis=0 along with numpy array for column deletion.
m=np.delete(m, 0, axis=0)     # its delete the 1st row.

# print the modified ndarray object on console.
print('Modified 2D Numpy Array by removing rows at index 0')
print(m) 

Containts of ndarray(a):
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
--------------------------------------------------
Modified 2D Numpy Array by removing rows at index 0
[[21 22 23 24]
 [31 32 33 34]]


In [9]:
# WAPP to delete a multiple rows from a 2D numpy array using np.delete().

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
m=np.array([[11 ,12, 13, 11],[21, 22, 23, 24],[31, 32, 33, 34]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(m)
print("-"*50)

# Delete elements from row index 1 and 2.
# place these indexes in one list and pass to delete function.
# pass the axis=0 along with numpy array for column deletion.
m=np.delete(m, [1,2], axis=0)     # its delete the 2st and 3rd rows.

# print the modified ndarray object on console.
print('Modified 2D Numpy Array by removing rows at index 1 and 2')
print(m) 

Containts of ndarray(a):
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
--------------------------------------------------
Modified 2D Numpy Array by removing rows at index 1 and 2
[[11 12 13 11]]


-----------------------------------------------------------------------------
### Delete specific elements in 2D Numpy Array by index position :
--------------------------------------------------------------------------------

- When we don’t pass axis argument to np.delete() then it’s default value is None, which means 2D numpy array will be 
  flattened for deleting elements at given index position.


In [10]:
# WAPP to delete element in row 0 and column 2 from 2D numpy array by using np.delete().

# create an object of ndarray. 
m=np.array([[11 ,12, 13, 11],[21, 22, 23, 24],[31, 32, 33, 34]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(m)
print("-"*50)

# Delete element in row 0 and column 2 from 2D numpy array.
m=np.delete(m, 2)     

# print the modified ndarray object on console.
'''When we don’t pass axis argument to np.delete() then it’s 
   default value is None, which means 2D numpy array will be 
   flattened for deleting elements at given index position.'''

print('Modified 2D Numpy Array by removing element at row 0 and column 2')
print(m)        # it returns flattened format.

Containts of ndarray(a):
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
--------------------------------------------------
Modified 2D Numpy Array by removing element at row 0 and column 2
[11 12 11 21 22 23 24 31 32 33 34]
