# <p style='text-align: center;'> Numpy Mathematical (Trigonometric) Operations. </p>

- Numpy contains the trigonometric functions which are used to calculate the sin, cos, tan, log and exp functions.

In [9]:
# WAPP to demonstrate the Mathematical (Trigonometric) Operations in Numpy.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([0,1,2,3,4,5])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# celculate the sin() of given ndarray object and print it.
print("printing the sin values of ndarray object") 
print(np.sin(a))
print("-"*50)

# celculate the cos() of given ndarray object and print it.
print("printing the cos values of ndarray object") 
print(np.cos(a))
print("-"*50)

# celculate the tan() of given ndarray object and print it.
print("printing the tan values of ndarray object") 
print(np.tan(a))
print("-"*50)

# celculate the exp() of given ndarray object and print it.
print("printing the exp() values of ndarray object") 
print(np.exp(a))
print("-"*50)

# celculate the log() of given ndarray object and print it.
print("printing the log values of ndarray object") 
print(np.log(a))
print("-"*50)

Containts of ndarray(a):
[0 1 2 3 4 5]
--------------------------------------------------
printing the sin values of ndarray object
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
--------------------------------------------------
printing the cos values of ndarray object
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
--------------------------------------------------
printing the tan values of ndarray object
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
--------------------------------------------------
printing the exp() values of ndarray object
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
--------------------------------------------------
printing the log values of ndarray object
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791]
--------------------------------------------------


C:\Users\Administrator\AppData\Local\Temp\ipykernel_14880\4274514059.py:36: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))
