# <p style='text-align: center;'> Numpy normal Operations </p>

## Numpy is mutable
- we can perform multiple operations on Numpy, they are

        1) Replacement
        2) Adding new elwments [ i) append(), ii)insert() ]
        3) Copy()
        4) around() 

In [1]:
# WAPP to replace the single value to given (1D) ndarray.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Replacing the value 5 as 20.
# pass the index number to ndarray object and place replacement value.
a[1] = 20     # its replace the index position 1 = 20.

# print the modified ndarray object on console.
print('Modified Numpy Array after replacement of element at index position 1')
print(a)      # its replaced value=5 to 20.

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
Modified Numpy Array after replacement of element at index position 1
[ 4 20  6  7  8  9 10 11]


In [2]:
# WAPP to replace the multiple values to given (1D) ndarray.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Replacing the value 4 as 2 and 11 as 33.
'''place these indexes in one list and pass the index number to ndarray 
   object and place replacement value.'''
a[[0,7]] = 2,33     # its replace the index position 0 = 2 and 7=33.

# print the modified ndarray object on console.
print('Modified Numpy Array after replacement of element at index position 1')
print(a)      # its replaced value=4 to 2 and 11 to 33.

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
Modified Numpy Array after replacement of element at index position 1
[ 2  5  6  7  8  9 10 33]


In [3]:
# WAPP to add the multiple values to given (1D) ndarray by using append().
# append()--will add elements at last only.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Add the values 4 2 and 11 to given (1D) ndarray by using append().
b=np.append(a,[4,2,11])

# print the modified ndarray object on console.
print(b)   # its added 4 2 and 11 values to original ndarray object.

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
[ 4  5  6  7  8  9 10 11  4  2 11]


In [6]:
# WAPP to add the multiple values to given (1D) ndarray by using insert().
# insert()--will add elements based on the index number.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Add the value 3 2 and 12 to given (1D) ndarray by using append().
# place the index numbers where you want to add these values.
#place these indexes in one list and pass to insert() function.
b=np.insert(a,[1,2,4],[3,2,12])    # Here [1,2,4] are index numbers.
                                   # Here [3,2,12] are New values.
    
# print the modified ndarray object on console.
print(b)   # its added 3 2 and 12 values to original ndarray object.

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
--------------------------------------------------
[ 4  3  5  2  6  7 12  8  9 10 11]


In [9]:
# WAPP to copy the given (1D) ndarray object by using copy().

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4,5,6,7,8,9,10,11])

# print the "a" ndarray object on console.
print("Containts of ndarray(a):")
print(a)
# print the id of "a" ndarray object on console.
print("id of ndarray(a):")
print(id(a))
print("-"*50)

# copy the "a" ndarray object to "b" ndarray object.
b=a.copy()          # it's shallow copy.

# print the "b" ndarray object on console.
print("Containts of ndarray(b):")
print(b)
# print the id of "b" ndarray object on console.
print("id of ndarray(b):")
print(id(b))

Containts of ndarray(a):
[ 4  5  6  7  8  9 10 11]
id of ndarray(a):
1907895490096
--------------------------------------------------
Containts of ndarray(b):
[ 4  5  6  7  8  9 10 11]
id of ndarray(b):
1907874501328


<b> around() :
- This mathematical function helps user to evenly round array elements to the given number of decimals.
    
    
- <b> Syntax : - numpy. around(arr, decimals = 0)
  
    
- Here arr is a ndarray object which we want to round it.
    
    
- decimals=0 is optional, if we not specified any value, then by default it returns int value.
  If we specified any value those number of decimals will be returned.

In [15]:
# WAPP to demonstrate around() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([4.1213,5.3435,6.4612,7.9898])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# apply the around() function to return int values from ndarray object.
# print the values with int.
print("Containts of ndarray(a) after around():")
print(np.around(a))    # it will returns the int values

# apply the around() function to return two decimal values from ndarray object.
# print the values with two decimals.
print("Containts of ndarray(a) with two decimals:")
print(np.around(a,2))  # it will returns the values with two decimals.

Containts of ndarray(a):
[4.1213 5.3435 6.4612 7.9898]
--------------------------------------------------
Containts of ndarray(a) after around():
[4. 5. 6. 8.]
Containts of ndarray(a) with two decimals:
[4.12 5.34 6.46 7.99]
