# <p style='text-align: center;'> Numpy Sorting Arrays </p>

- Sorting is nothing arranging the elements in an ordered sequence.


- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, 
  ascending or descending.


- The Numpy ndarray object has a function called sort(), that will sort a specified array.


- <b> Syntax : - numpy.sort(ndarrayobject)
    
    
- If you use the sort() method on a 2-D array, both columns and Rows of ndarray will be sorted.


-------------------------------
#### Examples :
-----------------------------

In [3]:
# WAPP to sort the given (1D) ndarray in ascending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([70,20,80,40,90,60])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Pass the array to the sort() method and Print the resultant array.
print("Containts of sorted array in ascending order:")
print(np.sort(a))

Containts of ndarray(a):
[70 20 80 40 90 60]
--------------------------------------------------
Containts of sorted array in ascending order:
[20 40 60 70 80 90]


In [4]:
# WAPP to sort the given (1D) ndarray in descending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([70,20,80,40,90,60])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

''' Pass the array to the sort() method and reverse the returned array using slicing 
    i.e array[::-1] and Print the resultant array.'''

print("Containts of sorted array in descending order:")
print(np.sort(a)[::-1])

Containts of ndarray(a):
[70 20 80 40 90 60]
--------------------------------------------------
Containts of sorted array in descending order:
[90 80 70 60 40 20]


In [5]:
# WAPP to sort the given (1D) ndarray in ascending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
b=np.array(["Ram","Kiran","Hari","Sonu","Mahesh"])

# print the ndarray object on console.
print("Containts of ndarray(b):")
print(b)
print("-"*50)

# Pass the array to the sort() method and Print the resultant array.
print("Containts of sorted array in ascending order:")
print(np.sort(b))

Containts of ndarray(b):
['Ram' 'Kiran' 'Hari' 'Sonu' 'Mahesh']
--------------------------------------------------
Containts of sorted array in ascending order:
['Hari' 'Kiran' 'Mahesh' 'Ram' 'Sonu']


In [6]:
# WAPP to sort the given (1D) ndarray in descending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
b=np.array(["Ram","Kiran","Hari","Sonu","Mahesh"])

# print the ndarray object on console.
print("Containts of ndarray(b):")
print(b)
print("-"*50)

''' Pass the array to the sort() method and reverse the returned array using slicing 
    i.e array[::-1] and Print the resultant array.'''

print("Containts of sorted array in descending order:")
print(np.sort(b)[::-1])

Containts of ndarray(b):
['Ram' 'Kiran' 'Hari' 'Sonu' 'Mahesh']
--------------------------------------------------
Containts of sorted array in descending order:
['Sonu' 'Ram' 'Mahesh' 'Kiran' 'Hari']


In [7]:
# WAPP to sort the given (2D) ndarray in ascending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([[80,60,90],[4,1,7]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Pass the array to the sort() method and Print the resultant array.
print("Containts of sorted array in ascending order:")
print(np.sort(a))

Containts of ndarray(a):
[[80 60 90]
 [ 4  1  7]]
--------------------------------------------------
Containts of sorted array in ascending order:
[[60 80 90]
 [ 1  4  7]]


In [8]:
# WAPP to sort the given (2D) ndarray in descending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
x=np.array([[80,60,90],[4,1,7]])

# print the ndarray object on console.
print("Containts of ndarray(x):")
print(x)
print("-"*50)

''' Pass the array to the sort() method and reverse the returned array using slicing 
    i.e array[::-1] and Print the resultant array.'''

print("Containts of sorted array in descending order:")
print(np.sort(x)[::-1])

Containts of ndarray(x):
[[80 60 90]
 [ 4  1  7]]
--------------------------------------------------
Containts of sorted array in descending order:
[[ 1  4  7]
 [60 80 90]]


In [18]:
# WAPP to sort the given (2D) ndarray in Column-Wise ascending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([[80,60,90],[4,1,7]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Pass the array to the sort() method and Print the resultant array.
print("Containts of sorted array in column_wise ascending order:")
print(np.sort(a,axis=0))         # axis=0 it will takes column-wise.

Containts of ndarray(a):
[[80 60 90]
 [ 4  1  7]]
--------------------------------------------------
Containts of sorted array in column_wise ascending order:
[[ 4  1  7]
 [80 60 90]]


In [17]:
# WAPP to sort the given (2D) ndarray in Column-Wise descending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
x=np.array([[80,60,90],[4,1,7]])

# print the ndarray object on console.
print("Containts of ndarray(x):")
print(x)
print("-"*50)

''' Pass the array to the sort() method and reverse the returned array using slicing 
    i.e array[::-1] and Print the resultant array.'''

print("Containts of sorted array in column_wise descending order:")
print(np.sort(x, axis=0)[::-1])    # axis=0 it will takes column-wise.

Containts of ndarray(x):
[[80 60 90]
 [ 4  1  7]]
--------------------------------------------------
Containts of sorted array in column_wise descending order:
[[80 60 90]
 [ 4  1  7]]


In [16]:
# WAPP to sort the given (2D) ndarray in Row-Wise ascending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
a=np.array([[80,60,90],[4,1,7]])

# print the ndarray object on console.
print("Containts of ndarray(a):")
print(a)
print("-"*50)

# Pass the array to the sort() method and Print the resultant array.
print("Containts of sorted array in Row-wise ascending order:")
print(np.sort(a,axis=1))         # axis=1 it will takes Row-wise.

Containts of ndarray(a):
[[80 60 90]
 [ 4  1  7]]
--------------------------------------------------
Containts of sorted array in Row-wise ascending order:
[[60 80 90]
 [ 1  4  7]]


In [13]:
# WAPP to sort the given (2D) ndarray in Row-Wise descending order by using sort() function.

# importing numpy as alias_name np
import numpy as np

# create an object of ndarray. 
x=np.array([[80,60,90],[4,1,7]])

# print the ndarray object on console.
print("Containts of ndarray(x):")
print(x)
print("-"*50)

''' Pass the array to the sort() method and reverse the returned array using slicing 
    i.e array[::-1] and Print the resultant array.'''

print("Containts of sorted array in Row-wise descending order:")
print(np.sort(x, axis=1)[::-1])    # axis=1 it will takes Row-wise.

Containts of ndarray(x):
[[80 60 90]
 [ 4  1  7]]
--------------------------------------------------
Containts of sorted array in Row-wise descending order:
[[ 1  4  7]
 [60 80 90]]
